POST http://localhost:3001/api/blogs/5f14a55105dddd9e743657c9/comments
Content-Type: application/json


{
  "likes": 0,
  "title": "Test blog 3679",
  "author": "Newson Lawson",
  "url": "newson.ca",
  "user": "5f02d4f182b5aa4b1d949174",
  "comments": ["Nice blog", "Nice blog"]
}
